### ISSUE TITLE
Clarify required component for MVP

### ISSUE THREAD

**Issue by frankobe** [bodhiproject/bodhi-api#11]
when docker configuration, I realize there are some components unclear:

1. is redis as request queue necessary? Can we remove it?
 * we will add one more redis component to the product -> increase failure points
 * memory consumption for redis is quite large 
* if keeping it, the request queue doesnt serve all requests from bodhi-graphql

2. does bodhi-api stand as a web service to redirect UI requests to qtum node or a bodhi smart contract wrapper? 
* Seems it starts on port 8080. bodhi-graphql stands as an express web service already, we need merge bodhi-api with bodhi-graphql to avoid duplicated web service
* if it is a wrapper, how to import this module?

**Comment by dwalintukan** [comment]
1. Redis doesn't look like a requirement. Just tested without redis running and it seems to work fine.
2. API is just for redirecting requests to local qtum node via http requests. I think for the MVP version we should try to cut out the API layer and directly call UI > qweb3. It would be one less service to spin up. What do you think?

**Comment by frankobe** [comment]
@dwalintukan cant agree more. But bodhi-ui is using bodhi-api to issue qtum requests now, right?

**Comment by dwalintukan** [comment]
@frankobe Correct, UI is using API currently for everything. Last part I left off is that the UI needed a proxy server to hit qweb3 directly.

**Comment by dwalintukan** [comment]
As discussed, we will leave this as API for the 26th version. Will look into removing the API layer after first beta release.
