### ISSUE TITLE
BodhiToken.balanceOf() result needs to be decoded

### ISSUE THREAD

**Issue by chrisli30** [bodhiproject/bodhi-api#18]
- [x] @dwalintukan , could you add decoding func to balanceOf()
- [x] The endpoint name /balanceOf is too general. What about making it something like botBalance?

Expected:
{
    "result": {
        "address": qtum address instead of hex, because input is qtum address,
       "balance": can be a string to prevent BN problem
   }
}

Current:
{
    "result": {
        "address": "f6177bc9812eeb531907621af6641a41133dea9e",
        "executionResult": {
            "gasUsed": 23343,
            "excepted": "None",
            "newAddress": "f6177bc9812eeb531907621af6641a41133dea9e",
            "output": "000000000000000000000000000000000000000000000000000009184e72a000",
            "codeDeposit": 0,
            "gasRefunded": 0,
            "depositSize": 0,
            "gasForDeposit": 0
        },
        "transactionReceipt": {
            "stateRoot": "efc9517a894a7489bb0c37b61096df03ad26b6d63c9dbeeb3259f5ef2fbf3530",
            "gasUsed": 23343,
            "bloom": "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
            "log": []
        }
    }
}

**Comment by chrisli30** [comment]
Even better, if we can also implement another endpoint called /botbalances which takes an array of address as input. That way frontend doesn't need to make multiple calls.

**Comment by dwalintukan** [comment]
^ Not possible to make batch calls since it needs to call each one by itself in cli.

**Comment by dwalintukan** [comment]
done

**Comment by dwalintukan** [comment]
Will create a qweb3 issue for this since it originates from there.
