### ISSUE TITLE
CreateTopic doesn't got through consistently

### ISSUE THREAD

**Issue by chrisli30** [bodhiproject/bodhi-api#23]
Only one out of three came out success. I don't know how to debug those events. Could you check below transactions? What would be a good way for us to debug transactions?

https://testnet.qtum.org/tx/bd39eefb2caf747a3fe2c0f90f1862ad6311f46d18a90881a43f0fd0441eff36

https://testnet.qtum.org/tx/32dd87a9322c94b32754f490f8fe03620264c50aa5cb698255b247fd99d68827

https://testnet.qtum.org/tx/87f2391e1dbe404decbb41d3f1201c77d10143f3a3af74a32a925ccf49dfa470

**Comment by chrisli30** [comment]
oh shoot, I have a theory. It could be because those Chinese titles are long. I tried a short tile it went through. But they are not longer than our limit though.

**Comment by dwalintukan** [comment]
fixed in qweb3 PR
